name: ruff
description: Run 'ruff'

branding:
  icon: activity
  color: gray-dark

inputs:
  token:
    description: GitHub Personal Access Token
    default: ${{github.token}}

runs:
  using: composite
  steps:
    - name: Check out repo
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Install 'ruff'
      uses: astral-sh/ruff-action@v3

    - name: Run 'ruff check --fix'
      run: ruff check --fix
      shell: bash

    - name: Run 'ruff format'
      run: ruff format
      shell: bash
